import numpy as np
a=np.array([[1,2],[3,4]])
print("Array is:")
print(a)
print("Sum is:")
print(a+2)
print("product is:")
print(a*2)
b=np.array([[5,6],[7,8]])
print("First numpy:")
print(a)
print("Second numpy:")
print(b)
print("Sum=")
print(a+b)
print("First numpy:")
print(a)
print("---------------")
print(a.sum())
print("---------------")
print(a.sum(axis=0))
print("---------------")
print(a.sum(axis=1))
print("---------------")
print(a.min())
